### PR TITLE
Feature/arbitrary json nix parsing

### PR DESCRIPTION
**Pull request by harrys522**
Heres a general refactor and cleanup alongside a more resilient (less hardcoded) version of the Studio API that should be compatible with the previous version too. I've aimed to improve readability and maintainability, as a reviewer if you are unable to run or understand any of this code please ask. 

The aim of this PR is for this repository to be stable and comprehensible to external parties.

### CODE REVIEW

**Comment by dowdt** [comment]
Ok, will check this out quickly.

**Review by dowdt — CHANGES_REQUESTED** [review]
Seems to work correctly. Only 2 changes needed.

1. run-studio should be changed to:
```
#!/bin/sh
python src/xnode_admin/main.py -p . https://dpl-staging.openmesh.network/xnodes/functions 0
```

2. Config.nix shouldn't be tracked by the repo, neither should latest_config.json.

**Comment by harrys522** [comment]
Changes made @dowdt

**Review by dowdt — APPROVED** [review]
Looks good :+1:

**Review by j-openmesh — APPROVED** [review]
LGTM

**Comment by harshu4** [comment]
Neat.

**Review by harshu4 — APPROVED** [review]

**Pull request merged**
