### PR TITLE
Permission granted to licence repository under MIT

### PR DESCRIPTION
**Pull request by harrys522**
I'm proposing MIT licence for this repository, this has been discussed previously. Let me know if you have any comments @j-openmesh & @dowdt , I'll need you to add your names as authors in the licence.

https://github.com/Openmesh-Network/xnode-admin/issues/5

### CODE REVIEW

**Comment by dowdt** [comment]
ack

**Review by dowdt — APPROVED** [review]
ack

**Review by j-openmesh — CHANGES_REQUESTED** [review]
See https://github.com/Openmesh-Network/XnodeOS/pull/16#pullrequestreview-2161781096

> Agree with MIT, however, copyright notice should read "XnodeOS authors and other contributors" to cover everyone. Individual files/modules/components can contain SPDX license notices and individual copyright notices, if desired.

In this case though, obviously, we'd use "Xnode-admin" instead of XnodeOS.

**Comment by harrys522** [comment]
@j-openmesh Thanks for the input, I've altered it, is that what you meant?

**Review by j-openmesh — APPROVED** [review]
:+1: I agree to MIT licence.

**Pull request merged**
